// получить всез пользователей
GET http://localhost:3000/users
Accept: application/json

###

// получить пользователя
GET http://localhost:3000/users/638c8b7cd3a5df155d78fee3
Accept: application/json

###

// получить все карточки
GET http://localhost:3000/cards
Accept: application/json

###

// создать нового пользователя (name, about, avatar)
POST http://localhost:3000/users
Content-Type: application/x-www-form-urlencoded

name=Колобок&about=Чудо-юдо-new&avatar=https://avatars.dzeninfra.ru/get-zen_doc/1595998/pub_5fe906cfe5cdbc6a96154adf_5fe9fd003ede826fd44bdbb3

###

// создать новую карточку (name, link)
POST http://localhost:3000/cards
Content-Type: application/x-www-form-urlencoded

name=Колобок&link=https://avatars.dzeninfra.ru/get-zen_doc/1595998/pub_5fe906cfe5cdbc6a96154adf_5fe9fd003ede826fd44bdbb3

###